### ISSUE TITLE
Fails poorly

### ISSUE THREAD

**Issue by raymondberg** [raymondberg/pytetris#3]
After the refactor I'm getting some errors on failure

```
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    Game().run()
  File "/home/rberg/rb/pytetris/pytetris/game.py", line 49, in run
    self.__update_board(board)
  File "/home/rberg/rb/pytetris/pytetris/game.py", line 60, in __update_board
    xx = game_over_image.get_width()
NameError: global name 'game_over_image' is not defined
```

**Comment by raymondberg** [comment]
Closed with     33df4b3
